import { environment } from '@env/environment';

export const URL_SYSTEM = environment.urlSystem;
export const STATUS = { SUCCESS: 0, ERROR: 500 };


export const PATH = {
    GENERATE_TOKEN: 'public/login',
    GET_GROUP_USER: 'public/group/index',
    REGISTER_USER: 'public/register',
    AUTO_GENERATE_TOKEN: 'generate-token-url',
    REVOKE_TOKEN: 'revoke-token',
    USER_INFO: 'user-info',
    ROLE: {
        GET_ALL_ROLE: 'role/get-all-role',
        CREATE_ROLE: 'role/create-role',
        UPDATE_ROLE: 'v1.0/role/update-role',
        DELETE_ROLE: 'role/delete-role',
        GET_ROLE_DETAIL: 'role/get-role-detail',
        GET_USER_IN_ROLE: 'role/get-user-in-role',
        GET_ALL_RIGHT: 'v1.0/right/get-all-right',
        ADD_USER_TO_ROLE: 'role/add-user',
        REMOVE_USER_IN_ROLE: 'role/remove-user',
        CREATE_RIGHT_IN_ROLE: 'role/create-right-in-role',
        GET_ALL_ROLE_WITH_COUNT: 'role/get-all-role-with-count',
        CREATE_MENU_IN_ROLE: 'role/create-menu-in-role',
        SEARCH_ROLE: 'user/search-role',
        CLEAN_RIGHT_MENU_IN_ROLE: 'role/clean-right-menu-in-role',
        UPLOAD_USER_ROLE_EXCEL: 'role/upload-user-role-excel',
    },
    RIGHT: {
        GET_ALL_RIGHT: 'right/get-all-right',
    },
    MENU: {
        GET_ALL_MENU: 'menu/get-all-menu',
        CREATE_MENU: 'menu/create-menu',
        UPDATE_MENU: 'menu/update-menu',
        DELETE_MENU: 'menu/delete-menu',
        GET_MENU_DETAIL: 'menu/get-menu-detail',
    },
    USER: {
        CREATE_USER: 'user/create-user',
        SEARCH_USER: 'user/search-user',
        UPLOAD_USER: 'user/upload-user-excel',
        DELETE_USER: 'user/delete-user',
    },
    JOB: {
        DELETE_JOB: 'scheduler/delete-job',
        GET_ALL_JOB: 'scheduler/get-all-job',
        GET_ALL_JOB_EXECUTED: 'scheduler/get-all-job-executed',
        GET_JOB_DETAIL: 'scheduler/get-job-detail',
        PAUSE_JOB: 'scheduler/pause-job',
        REGISTER_JOB: 'scheduler/register-job',
        RESUME_JOB: 'scheduler/resume-job',
        UNSCHEDULE_JOB: 'scheduler/unschedule-job',
        UPDATE_JOB: 'scheduler/update-job',
        START_JOB_NOW: 'scheduler/start-job-now',
    },
    REDIS: {
        GET_ALL_REDIS: 'redis/get-all-key',
        RESET_KEY_BY_ID: 'redis/reset-key',
        RESET_ALL_KEY: 'redis/reset-all-key',
    },
    MONITOR: {
        GET_ALL_MONITOR: 'log/search-action-log',
        GET_ALL_EMAIL_LOG: 'email/searchEmailLog',
    },
    PROCESS: {
        SEARCH_PROCESS_INSTANCE: 'process/search-process-instance',
        SEARCH_PROCESS_INSTANCE_DETAIL: 'process/get-process-instance-detail',
        GET_ALL_PROCESS_DEFINITION: 'process/get-all-process-definition',
        DEPLOY_PROCESS: 'process/deployProcess',
        CANCEL_PROCESS: 'process/cancel-process',
    },
    PROCESS_SERVICE_CONFIG: {
        SEARCH_PROCESS: 'process-service-config/search-process',
    },
    TASK: {
        GET_ALL_TASK_TYPE: 'task/get-all-task-type',
        SEARCH_TASK: 'task/search-task',
        ACCEPT_TASK: 'task/accept-task',
        ASSIGN_TASK: 'task/assign-task',
        CANCEL_TASK: 'task/cancel-task',
        RESUME_TASK: 'task/resume-task',
        SUSPEND_TASK: 'task/suspend-task',
        DELETE_TASK: 'task/delete-task',
        SEARCH_USER_LIST: 'task/get-reassigned-user-list',
        SEARCH_ASSIGN_TASK_LOG: 'task/get-user-task',
        TASK_DETAIL: 'common/v1.0/get-task-detail',
    },
    SITE: {
        GET_ALL_SITE: 'site/get-all-site',
    },
    STEP: {
        SEARCH_STEP_HISTORY: 'step/get-step-history-list',
        UPDATE_STEP_DATA: 'step/update-step-data',
        RESUBMIT_STEP: 'step/resubmit-step',
        GET_STEP_INSTANCE: 'step/get-step-instance',
    },
    RULE: {
        SEARCH_RULE_HO: 'rule/search-rule-ho',
        CREATE_RULE_HO: 'rule/create-rule-ho',
        UPDATE_RULE_HO: 'rule/update-rule-ho',
        DELETE_RULE_HO: 'rule/delete-rule-ho',
        SEARCH_RULE_BRANCH: 'rule/search-rule-branch',
        CREATE_RULE_BRANCH: 'rule/create-rule-branch',
        UPDATE_RULE_BRANCH: 'rule/update-rule-branch',
        DELETE_RULE_BRANCH: 'rule/delete-rule-branch',
    },
    TEMPLATE: {
        GET_ALL_TEMPLATE: 'template/search-file-template',
        DELETE_FILE_TEMPLATE: 'template/delete-file-template',
        DOWNLOAD_FILE_TEMPLATE: 'template/download-file-template',
        UPLOAD_FILE_TEMPLATE_EXCEL: 'template/upload-file-template-excel',
        GET_ALL_EMAIL_TEMPLATE: 'template/search-email-template',
        CREATE_OR_UPDATE_EMAIL_TEMPLATE: 'template/create-email-template',
        DELETE_EMAIL_TEMPLATE: 'template/delete-email-template',
    },
    FIRST_CHECK: {
        CHECK_POLICY: 'first-check/check-policy',
        SEARCH_FIRST_CHECK: 'first-check/get-all-first-check',
        GET_FIRST_CHECK_DETAIL: 'first-check/get-first-check-detail',
    },
    CATEGORY: {
        LOAN_TYPE: 'category/loan-type',
        PRODUCT: 'category/product',
        CATEGORIES: 'category/categories',
    },
    CUSTOMER_INFO: {
        GET_CUSTOMER_T24: 'customer-info/get-customer-t24',
    },
    TASK_INBOX: {
        SEARCH_TASK_ACTIVE: 'task-inbox/search-task-active',
    },
    ADVICE: {
        START_PROCESS: 'advise-process/v1.0/start-advise-process',
        SAVE_TASK_DATA:'advise-process/v1.0/advise/save-task-data',
        COMPLETE_TASK: 'advise-process/v1.0/complete-task',
        EXPORT_FILE: 'advise-process/v1.0/export-file',
        GET_ADVICE_DATA_FOR_COPY: 'advise-process/v1.0/advise/get-advise-data-for-copy',
        ABORT_TASK: 'advise-process/v1.0/cancel-process-by-bpmid',
        GET_ADVICE_DATA_FOR_VIEW: 'advise-process/v1.0/advise/get-advise-data-for-view',
        SEND_EMAIL: "advise-process/v1.0/send-email",
    },
    AMEND: {
        START_PROCESS: 'amend-process/v1.0/start-amend-process',
        SAVE_TASK_DATA:'amend-process/v1.0/save-task-data',
        EXPORT_FILE: 'amend-process/v1.0/export-file',
        COMPLETE_TASK: 'amend-process/v1.0/complete-task',
        ABORT_TASK: 'amend-process/v1.0/cancel-process-by-bpmid',
        GET_AMEND_DATA_FOR_VIEW: 'amend-process/v1.0/get-amend-data-for-view',
        SEND_EMAIL: "amend-process/v1.0/send-email",
        GET_AMEND_DATA_APPR: "amend-process/v1.0/get-amend-data-appr",
        GET_AMEND_DATA_NEWEST_BY_LC: "amend-process/v1.0/get-amend-data-newest-by-lc",
    },
    PRESENT_DOC: {
        START_PROCESS: 'present-process/v1.0/start-present-process',
        ABORT_TASK: 'present-process/v1.0/cancel-process-by-bpmid',
        SAVE_TASK_DATA:'present-process/v1.0/save-task-data',
        GET_PRESENT_DATA_FOR_COPY:'present-process/v1.0/get-present-data-for-copy',
        GET_PRESENT_DATA_FOR_VIEW:'present-process/v1.0/get-present-data-for-view',
        COMPLETE_TASK: 'present-process/v1.0/complete-task',
        EXPORT_FILE: 'present-process/v1.0/export-file',
        GET_LATEST_COVER_PRESENT_DATA: 'present-process/v1.0/get-latest-cover-present-data',
        GET_PRESENT_DOC_GOOD: 'present-process/v1.0/get-present-doc-good',
        SAVE_PRESENT_DOC_GOOD: 'present-process/v1.0/save-present-doc-good',
        SEND_EMAIL: "present-process/v1.0/send-email",
        CHECK_PRESENT_DATA_FOR_FILL_CHARGE: "present-process/v1.0/check-present-data-for-fill-chare",
        GET_PRESENT_DOC_LIST: "present-process/v1.0/get-present-doc-list",
        GET_DHL_NUMBER: 'present-process/v1.0/get-dhl-number',
        GET_DHL_INFO_KAFKA: 'present-process/v1.0/get-dhl-info-kafka',
    },
    MESSAGE: {
        START_PROCESS: 'message-process/v1.0/start-message-process',
        SAVE_TASK_DATA:'message-process/v1.0/save-task-data',
        EXPORT_FILE: 'message-process/v1.0/export-file',
        COMPLETE_TASK: 'message-process/v1.0/complete-task',
        ABORT_TASK: 'message-process/v1.0/cancel-process-by-bpmid',
        GET_MESSAGE_DATA_FOR_VIEW: 'message-process/v1.0/get-message-data-for-view',
        SEND_EMAIL: "message-process/v1.0/send-email",
        GET_MESSAGE_COPY: "message-process/v1.0/get-message-data-for-copy",
        GET_PRESENT_DATA_BY_LC: "message-process/v1.0/get-present-data-by-lc",
        GET_MESSAGE_BY_LCNUMBER: "message-process/v1.0/get-message-data-by-lc-number",
        GET_MESSAGE_VIEW_DETAIL: 'message-process/v1.0/get-message-data-view-detail',
    },
    COMMON:{
        TRACKING:'common/v1.0/get-tracking-by-bpmid',
        GET_BRANCH_OFFICE_INFO:'common/v1.0/get-branch-office-info-by-id',
        INSERT_COMMENT:'common/v1.0/insert-comment',
        GET_CAT_BRANCH_BY_BRANCH_ID: 'common/v1.0/get-cat-branch-by-branchid',
        GET_LCXK_TRANS_INFO: 'common/v1.0/get-lcxk-trans-info',
        GET_LIST_PROCESS: 'common/v1.0/get-list-process',
        GET_CAT_STATUS_BY_PROCESS_ID: 'common/v1.0/get-cat-status-by-processid',
        GET_CHARGE_BY_BPM_ID: 'common/v1.0/get-charge-by-bpm-id',
        GET_MT_N99_BY_BPM_ID: 'common/v1.0/get-mt-n99-by-bpm-id',
        CHECK_CHANGE: 'common/v1.0/check-change',
        UPDATE_CUS_EMAIL: 'common/v1.0/update-cust-email',
        GET_CUST_INFO: 'common/v1.0/get-cust-info',
        GET_COMMON_LC_INFO: 'common/v1.0/get-common-lc-info',
        GET_LCXK_QUEUE_FOLLOW: 'common/v1.0/get-lcxk-queue-follow',
        UPDATE_LCXK_QUEUE_FOLLOW: 'common/v1.0/update-lcxk-queue-follow',
        DELETE_LCXK_QUEUE_FOLLOW: 'common/v1.0/delete-lcxk-queue-follow',
        GET_NOTE: 'common/v1.0/get-note',
        CAT_PARAM: 'common/v1.0/get-cat-param',
        CAT_PARAM_LCNK: 'common/v1.0/get-cat-param-lcnk',
        GET_SWCODE_BY_CUS_ID: 'common/v1.0/get-swiftcode-by-cusid',
        GET_BRANCH_INFO_BY_ID: 'common/v1.0/get-branch-info-by-id',
        GET_BRANCH_INFO_BY_PAYMENT_CENTER: 'common/v1.0/get-branch-info-by-payment-center',
        CUS_ID_BY_SWCODE: 'common/v1.0/get-cusid-by-swiftcode',
        USER_INFO_BY_USERID: 'common/v1.0/get-user-info-by-userid',
        GG_CHARGE_BY_ID: 'common/v1.0/get-gg-charge-by-id',
        GET_COMMENT: 'common/v1.0/get-comment',
        VALIDATE_CHECKLIST: 'common/v1.0/validate-checklist',
        CHECK_DAY_OFF_WORK: 'common/v1.0/check-day-off-work',
        ADD_TIME_MINUTES: 'common/v1.0/add-time-minutes',
        GET_CAT_LIBRARY: 'common/v1.0/get-cat-library',
        GET_CAT_NOSTRO: 'common/v1.0/get-cat-nostro',
        VALIDATE_VIEW_TRANS_BY_USER_ID: 'common/v1.0/validate-view-trans-by-user-id',
        GET_LCXK_INPROCESS_TRANS: 'common/v1.0/get-lcxk-inprocess-trans',
        UPDATE_STATUS_ABORT: 'common/v1.0/abort-process',
        GET_LCXK_INPROCESS_COMPLETED_TRANS: 'common/v1.0/get-lcxk-inprocess-completed-trans',
        TASK_DETAIL: 'common/v1.0/get-task-detail',
        GET_USER_IN_ROLE: 'common/v1.0/get-user-in-role',
        GET_ROLE_BY_USER: 'common/v1.0/get-role-by-user',
        GET_STATUS_BY_ROLE: 'common/v1.0/get-status-by-role',
        GET_TASK_ACTIVE_ASSIGN: 'common/v1.0/get-task-active-assign',
        UPDATE_USER_ASSIGN_TASK:'common/v1.0/update-user-assign-task',
        ADD_ASSIGN_TASK_LOG:'common/v1.0/add-assign-task-log',
        GET_TASK_ASSIGN_LOG: 'common/v1.0/get-task-assign-log',
        SYNC_CUSTOMER_FILE: 'common/v1.0/sync-customer-file',
        GET_BRANCH_INFO: 'common/v1.0/get-branch-info',
        UPDATE_BRANCH_INFO: 'common/v1.0/update-branch-info',
        GET_AML_PLUS: 'common/v1.0/get-aml-plus',
        GET_SWIFT_BODY: 'common/v1.0/get-swift-body-bpm',
        GET_DRAWING_AUDIT_INFO: 'common/v1.0/get-drawing-audit-info',
        FIND_MSG_ID_BY_F20: 'common/v1.0/find-msg-id-by-f20',
        GET_MT7XX_DETAIL: "common/v1.0/get-mt7xx-detail",
        GET_FOLLOW_QUEUE_APPROVAL: "common/v1.0/get-lcxk-queue-follow-approval",
        DELETE_FOLLOW_QUEUE_APPROVAL: "common/v1.0/delete-lcxk-queue-follow-approval",
        GET_ADVICE_INFO_BY_LC_NO: "common/v1.0/get-advice-info-by-lc-no",
        GET_AMEND_INFO_BY_LC_NO: "common/v1.0/get-amend-info-by-lc-no",
        GET_GG_RECORD_NUMBER_BY_TF_NUMBER: "common/v1.0/get-gg-record-number-by-tf-number",
        GET_DASHBOARD_DISTRIBUTE: "common/v1.0/get-dashboard-distribute",
        GET_DASHBOARD_FINAL_LIST: "common/v1.0/get-dashboard-final-list",
        GET_DASHBOARD_FINAL_LIST_NEW: "common/v1.0/get-dashboard-final-list-new",
        GET_DASHBOARD_SLGD: "common/v1.0/get-dashboard-slgd",
        GET_DASHBOARD_SLGD_NEW: "common/v1.0/get-dashboard-slgd-new",
        GET_USER_BY_ROLE_ID: "common/v1.0/get-user-by-role-id",
        GET_USER_BY_ROLE_ID_ALL: "common/v1.0/get-user-by-role-id-all",
        EXPORT_FILE_DASHBOARD_DISTRIBUTE:"v1.0/dashboard-distribute-export",
        GET_LATEST_TASK_ID: 'common/v1.0/get-latest-task-by-custom-task-id',
        PUSH_NOTIFICATION_BIZ: 'common/v1.0/push-notification-biz',
        SEND_EMAIL_ASSIGN_TASK: 'common/v1.0/send-email-assign-task'
    },
    DOCUMENT: {
        GET_DOC: 'common/v1.0/get-doc',
        GET_DOC_ADD_DOC: 'common/v1.0/get-doc-add-doc',
    },
    INTERGRATE: {
        CUSTOMER_INFO: 'intergrate/v1.0/get-customer-info',
        GET_LCXK_BY_LC_NO: 'intergrate/v1.0/get-lcxk-by-lcno',
        SWIFT_IN: 'intergrate/v1.0/get-swift-in',
        LC_REF: 'intergrate/v1.0/get-message-info-by-lc-ref',
        CHARGE_AMOUNT: 'intergrate/v1.0/get-charge-amount',
        CREATE_LCXK: 'intergrate/v1.0/create-lcxk',
        CREATE_AUT_FM: 'intergrate/v1.0/create-aut-fM',
        CREATE_AUT_FM_NONE_AML: 'intergrate/v1.0/create-aut-fM-none-aml',
        LC_INFO_NEW: 'intergrate/v1.0/get-lc-infor-new',
        FM_INFO_NEW: 'intergrate/v1.0/get-fm-info-new',
        GET_FM_FT_MESSAGE_BODY_NEW: 'intergrate/v1.0/get-fm-ft-message-body-new',
        GET_INTERNATIONAL_TRANSACTION_INFO_NEW: 'intergrate/v1.0/get-international-transaction-info-new',
        TF_RESULT: 'intergrate/v1.0/get-tf-result',
        GET_LC_LIST: 'intergrate/v1.0/get-lc-list',
        GET_EXCHANGE_RATE: 'intergrate/v1.0/get-exchange-rate',
        GET_CUST_ACCT: 'intergrate/v1.0/get-cust-acct',
        CREATE_DR: 'intergrate/v1.0/create-dr',
        CHANGE_TYPE_DR: 'intergrate/v1.0/change-type-dr',
        DR_INFO: 'intergrate/v1.0/get-dr-info',
        AUTHORISE_DR: 'intergrate/v1.0/authorise-dr',
        CHECK_AML_STATUS: 'intergrate/v1.0/check-aml-status',
        SCAN_AML: 'intergrate/v1.0/scan-aml',
        CREATE_CHARGE: 'intergrate/v1.0/create-charge',
        GUARANTEE: 'intergrate/v1.0/get-message-info-by-guarantee',
        SCAN_TF: 'intergrate/v1.0/scan-tf',
        CANCEL_TF: 'intergrate/v1.0/tf-cancel',
        GET_DETAIL_ACCT_NO: 'intergrate/v1.0/get-info-account-list',
        FT_INFO: 'intergrate/v1.0/get-ft-info',
        GET_CREATE_FT: 'intergrate/v1.0/create-ft',
        GET_TRUST_RATING_ORS: 'intergrate/v1.0/get-trust-rating-ors',
    },
    BUSINESS_CALENDAR: {
        IS_DAY_OFF_WORK: 'business-calendar/is-day-off-work',
        ADD: 'business-calendar/add',
    },
    OPN:{
        INSERT_USER_ROLE_OPN: 'insert-user-role-opn',
        REMOVE_ROLE_OPN: 'remove-role-opn',
        REMOVE_USER_ROLE_OPN: 'remove-user-role-opn',
        UPDATE_USER_OPN: 'update-user-opn',
    },
    EVALUATE: {
        START_PROCESS: 'evaluate-process/v1.0/start-evaluate-process',
        ABORT_TASK: 'evaluate-process/v1.0/cancel-process-by-bpmid',
        SAVE_TASK_DATA:'evaluate-process/v1.0/save-task-data',
        GET_EVALUATE_DATA_FOR_COPY:'evaluate-process/v1.0/get-evaluate-data-for-copy',
        GET_EVALUATE_DATA_FOR_VIEW:'evaluate-process/v1.0/get-evaluate-data-for-view',
        GET_EVALUATE_DATA_FOR_REP_EMAIL:'evaluate-process/v1.0/get-evaluate-data-for-rep-email',
        COMPLETE_TASK: 'evaluate-process/v1.0/complete-task',
        EXPORT_FILE: 'evaluate-process/v1.0/export-file',
        SEND_EMAIL: "evaluate-process/v1.0/send-email",
        IS_LC_MESSAGE_SEND: 'evaluate-process/v1.0/is-lc-message-send'
    },
    ADD_DOC: {
        COMPLETE_TASK: 'add-doc-process/v1.0/complete-task',
        SAVE_TASK_DATA: 'add-doc-process/v1.0/save-task-data',
        START_PROCESS: 'add-doc-process/v1.0/start-add-doc-process',
        ABORT_TASK: 'add-doc-process/v1.0/cancel-process-by-bpmid',
        GET_REF_ADD_DOC_INFO: 'add-doc-process/v1.0/get-ref-add-doc-info',
        GET_STATUS_BY_ROLE: 'add-doc-process/v1.0/get-status-id-by-role',
        GET_DOC_CODE_OVERRIDE: 'add-doc-process/v1.0/get-doc-code-override',
        GET_ADD_DOC_FOR_VIEW: 'add-doc-process/v1.0/get-add-doc-for-view',
    },
    TRACING_PRESENT_DOC: {
        START_PROCESS: 'tracing-process/v1.0/start-tracing-process',
        COMPLETE_TASK: 'tracing-process/v1.0/complete-task',
        SAVE_TASK_DATA:'tracing-process/v1.0/save-task-data',
        GET_OLD_TRACING: 'tracing-process/v1.0/get-old-tracing-same-parent',
        GET_TRACING_PRESENT_DOC: 'tracing-process/v1.0/get-lcxk-tracing-present-doc-init-list',
        EXPORT_FILE: 'tracing-process/v1.0/export-file',
        SEND_EMAIL: "tracing-process/v1.0/send-email",
        GET_TRACING_DATA_FOR_VIEW_DETAIL: 'tracing-process/v1.0/get-tracing-data-for-view-detail'
    },
    CONSULT: {
        START_PROCESS: 'consult-process/v1.0/start-consult-process',
        COMPLETE_TASK: 'consult-process/v1.0/complete-task',
        ABORT_TASK: 'consult-process/v1.0/cancel-process-by-bpmid',
        SAVE_TASK_DATA:'consult-process/v1.0/save-task-data',
        EXPORT_FILE: 'consult-process/v1.0/export-file',
        SEND_EMAIL: "consult-process/v1.0/send-email",
        GET_CONSULT_DATA_FOR_VIEW_DETAIL: 'consult-process/v1.0/get-consult-data-for-view-detail',
        GET_CONSULT_PRESENT_DIFFERENCE_INFO: 'consult-process/v1.0/get-present-difference-info-by-bpm-id',
        GET_CONSULT_RATING: "consult-process/v1.0/get-consult-rating",
        GET_CONSULT_TRANSACTION_BEFORE: "consult-process/v1.0/get-consult-transaction-before",
        GET_LC_NO_BY_BIZ_ID: "consult-process/v1.0/get-lc_no-by-biz_id"
    },
    MANUAL_TRADING: {
        SAVE_MANUAL_TRADING: 'v1.0/manual-tranding',
        UPDATE_MANUAL_TRADING: 'v1.0/manual-tranding',
        LOAD_MANUAL_TRADING_PORTFOLIO: 'v1.0/manual-trading-ho-receive',
        LOAD_CHARGES: 'v1.0/manual-trading-cat-params',
        LOAD_USER_HO: 'v1.0/manual-trading-user-ho',
        DELETE_MANUAL_TRADING: 'v1.0/manual-trading',
        EXPORT_MANUAL_TRADING: 'v1.0/manual-trading-export',
        LOAD_MANUAL_ID: 'v1.0/manual-trading-id',
        LOAD_ROLE_USER_ID: 'v1.0/manual-trading-role'
    },
    ADVICE_CHARGE: {
        START_PROCESS: 'advice-charge/v1.0/start-process',
        COMPLETE_TASK: 'advice-charge/v1.0/complete-task',
        SAVE_TASK_DATA:'advice-charge/v1.0/save-task-data',
        GET_ADVICE_AND_AMEND:'advice-charge/v1.0/get-amend-and-advice',
        SEARCH_ADVICE_AND_AMEND:'advice-charge/v1.0/search-amend-and-advice',
        EXPORT_FILE: 'advice-charge/v1.0/export-file',
        ABORT_TASK: 'advice-charge/v1.0/cancel-process-by-bpmid',
        LIST_CHARGE_CODE: 'intergrate/v1.0/list-charge-code',
        COUNT_CHARGE_CODE: 'intergrate/v1.0/count-charge-code',
        GET_NOSTRO_ACCOUNT_LIST: 'intergrate/v1.0/get-nostro-account-list',
        GET_RECEVING_ADD: 'advice-charge/v1.0/get-receving-add',
        SEARCH_RECEVING_ADD: 'advice-charge/v1.0/search-receving-add',
        GET_NAME: 'intergrate/v1.0/make-transfer-name',
        CREATE_FT_INHOUSE: 'intergrate/v1.0/make-transfer',
        GET_CURRENCY_CODE: 'intergrate/v1.0/get-currency-code',
        GET_INFO_FT: 'intergrate/v1.0/get-ft-info',
        GET_FT_BY_TRANSACTION_REF: 'intergrate/v1.0/make-transfer-transaction',
        GET_ADVICE_CHARGE_DATA_FOR_VIEW_DETAIL: 'advice-charge/v1.0/get-advice-charge-data-for-view-detail'
    },
    ASYNC_FILE: {
        FILE: 'async-file/v1.0/file'
    },
    CHAT: {
        GENERATE_CHAT_PLUGIN: 'chat/v1.0/get-chat-plugin',
        CREATE_GROUP_CHAT: 'chat/v1.0/create-group-chat',
        GET_LIST_GROUP_ON_OFF: 'chat/v1.0/get-list-group-on-off',
        JOIN_GROUP_CHAT: 'chat/v1.0/join-group-on-off',
    },
    TRUST_RATING: {
        SEND_MESSAGE: 'trust-rating/v1.0/send-message',
        GET_TRUST_RATING_BPM: 'common/v1.0/get-trust-rating-bpm',
    },
    DHL: {
        SEND_MESSAGE: 'dhl/v1.0/send-message',
        SEND_MESSAGE_TEST: 'dhl/v1.0/send-message-test',
        GET_USER: 'dhl/v1.0/get-user',
        UPDATE_USER: 'dhl/v1.0/update-user',
        GET_DHL_BPM: 'dhl/v1.0/get-dhl-bpm'
    }
};

export enum RESPONSE_MESSAGE {
    SUCCESS = 'Success!',
}

export enum REQUEST_STATUS_FCRM {
    NEW = 'NEW',
    EDITED = 'EDITED',
    CANCELLED = 'CANCELLED',
}
