export class FtInfo{
    debitAccountNo? : string;
    amount? : string;
    amountCurrency? : string;
    creditAccountNo? : string;
    creditValueDate? : string;
    f20TransactionRefNumber? : string;
    f21RelatedReference? : string;
    f56Intermediary? : string;
    f56AIntermediaryBank? : string;
    f56DIntermediaryBankAccount? : string;
    f57AccountWithInstitution? : string;
    f57AAccountWithBank? : string;
    f57AAccountWithBankAccount?: string;
    f57DAccountWithBank? : string;
    f57DAccountWithBankAccount? : string;
    f58BeneficiaryInstitution? : string;
    f58ABeneficiaryBank? : string;
    f58ABenBankAccount?: string;
    f58DBeneficiaryBank? : string;
    f58DBenBankAccount? : string;
    f72ZSenderReceiverInformation1? : string;
    f72ZSenderReceiverInformation2? : string;
    f72ZSenderReceiverInformation3? : any[];
    paymentDetail? : any;
    ftNumber?: string;
    ftStatus?: string;
    debitAcctNo?: string;
    debitCurrency?: string;
    debitAmount?: string;
    creditAcctNo?: string;
    creditCurrency?: string;
    creaditAmount?: string;
    benAcctNo?: string;
    benBank?: string;
    commissionType?: string;
    bkToBkOut?: string;
    acctWithBank?: string;
    phoneNumber?: string;
    txnPurpose?: string;
    debitValueDate?: string;
    ftAml?: string
}
