#Chi sua gia tri, khong thay doi key
# So luong pod duoc tao
replicaCount: 1

# Khai bao service
service:
  type: NodePort
  nodePort: 10406
  port: 10406
  targetPort: 10406

# Khai bao gRPC service
gRPCEnable: false
gRPCService:
  nodePortgrpc: 10780
  portgrpc: 10780

# Khai bao hostnames
hostAliases:
  10.1.18.193: esbinternal.mbbank.com.vn
  10.1.12.164: esbinternet.mbbank.com.vn
  10.1.18.195: esbinternal.mbbank.com.vn
   
# Khai bao su dung configmap
configMaps:
  - nginx-custom.conf

# Khai bao su dung PVC
pvc: false
namePVC: 
  - pvc-cmv
  - pvc-crm-next-gen

# Khai bao volumeMount
volumeMountsMap:
  mountPathconfig: /deployment/config
  mountPathpodinfo: /deployment/podinfo   
  mountPathPVC:
    pvc-cmv: /data
    pvc-crm-next-gen: /crmdata
  
#Khai bao tai nguyen su dung cho pod
resources:
  limits:
    memory: 2Gi
  requests:
    memory: 1Gi

# Khai bao promethus
promethus: false
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: /tracing/actuator/prometheus
  prometheus.io/port: "10406"
  
# Khai bao label cho istio
labels: false
templateLabels:
  version: old
  sidecar.istio.io/inject: "true"

# Khai bao HealthCheck
healthCheck: false
startupProbe:
  failureThreshold: 10
  httpGet:
    path: /tracing/actuator/health
    port: 10406
    scheme: HTTP
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 2
livenessProbe:
  failureThreshold: 10
  httpGet:
    path: /tracing/actuator/health/liveness
    port: 10406
    scheme: HTTP
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 2
readinessProbe:
  failureThreshold: 10
  httpGet:
    path: /tracing/actuator/health/readiness
    port: 10406
    scheme: HTTP
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 2

# Khai bao bien moi truong 
ENV_PROFILE: dev
JVM_OPTS: -Xms512m -Xmx2048m -Dsun.net.http.retryPost=false -Dhttp.retryPost=false -noverify
  
serviceAccount:
  create: false

# Chi dinh pod chay tren node co dinh(chi dung tren live: default hoac ecm)
NodeSelectorEnable: false
nodeName: default

# Khai bao hpa thi de gia tri hpa true,,nguoc lai de false
autoscaling:
  enabled: false
  minPodsHPA: 2
  maxPodsHPA: 4
  #cpuHPA: 80
  memoryHPA: 80


# So lan deploy Helm
numberHelm: H1

# Thong tin image
image:
  repository: image_version
  pullPolicy: Always
  tag: "image_tag"


# Khai bao secret-registry harbor
imagePullSecrets:
 - name: harbor-secret-registry

## Tao ServiceAccout
serviceAccount:
  create: false
